# Generated by Django 4.1 on 2023-12-01 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Назване курса"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
                (
                    "images",
                    models.ImageField(
                        null=True, upload_to="img/", verbose_name="Превью курса"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=13, verbose_name="Стоимость курса"
                    ),
                ),
                ("studying_time", models.DurationField(verbose_name="Время обучения")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Навык")),
                ("description", models.TextField(verbose_name="Описание навыка")),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Тэг"),
                ),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Специализация"),
                ),
                (
                    "course",
                    models.ManyToManyField(
                        related_name="track", to="course.course", verbose_name="Курсы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "greate",
                    models.CharField(
                        choices=[("J", "Junior"), ("M", "Middle"), ("S", "Senior")],
                        default="J",
                        max_length=1,
                        verbose_name="Квалификация",
                    ),
                ),
                (
                    "accordance",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=1, message="Минимальный процент навыка"
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=100, message="Максимальный процент навыка"
                            ),
                        ],
                        verbose_name="Процент соответствия",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_track",
                        to="course.track",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_track",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление пользователя",
                "verbose_name_plural": "Направления пользователя",
                "ordering": ["accordance"],
            },
        ),
        migrations.CreateModel(
            name="SkillsTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=1, message="Минимальный процент навыка"
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=100, message="Максимальный процент навыка"
                            ),
                        ],
                        verbose_name="Процент соответствия",
                    ),
                ),
                (
                    "skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_track",
                        to="course.skill",
                        verbose_name="Навык",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_track",
                        to="course.track",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык для направления",
                "verbose_name_plural": "Навыки для направления",
                "ordering": ["track"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(
                related_name="curse", to="course.tag", verbose_name="Тэги курса"
            ),
        ),
    ]
