# Generated by Django 4.1 on 2023-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='level_skill_id',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='modul',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='theme_id',
        ),
        migrations.AddField(
            model_name='course',
            name='modul_id',
            field=models.ManyToManyField(related_name='course', to='course.modul', verbose_name='Модуль'),
        ),
        migrations.AddField(
            model_name='modul',
            name='theme_id',
            field=models.ManyToManyField(related_name='modul', to='course.theme', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='сourse_id',
            field=models.ManyToManyField(related_name='user_course', to='course.course', verbose_name='Курсы'),
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='links_id',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='pract_id',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='links_id',
            field=models.ManyToManyField(related_name='user_course', to='course.links', verbose_name='Ссылки'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='pract_id',
            field=models.ManyToManyField(related_name='user_course', to='course.pract', verbose_name='Практика'),
        ),
    ]
