import testImage1 from '../Images/svgexport-18.svg';
export const intialCards = [
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С нуля',
    title: 'Адаптивность',
    image: testImage1,
    price: 0,
  },
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С опытом',
    title: 'Валидация и улучшение',
    image: testImage1,
    price: 0,
  },
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С нуля',
    title: 'A/B тестирование',
    image: testImage1,
    price: '140000',
    monthly_price: '1567',
  },
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С нуля',
    title: 'Личность бренда',
    image: testImage1,
    price: '140000',
    monthly_price: '7201',
  },
  {
    profession: 'Дизайн',
    type: 'Модуль',
    level: 'С нуля',
    title: 'Aдаптивность',
    image: testImage1,
    price: '140000',
    monthly_price: '7201',
  },
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С опытом',
    title: 'Валидация и улучшение',
    image: testImage1,
    price: 0,
  },
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С нуля',
    title: 'A/B тестирование',
    image: testImage1,
    price: '140000',
    monthly_price: '1567',
  },
  {
    profession: 'Дизайн',
    type: 'Урок',
    level: 'С нуля',
    title: 'Личность бренда',
    image: testImage1,
    price: '140000',
    monthly_price: '7201',
  },
];
