export const UXSEARCHING = 'UX-исследования'
export const UIDESIGN = 'UI-дизайн'
export const TOOLS = 'Инструменты'
export const COMMUNICATION = 'Коммуникация'
export const TOGROWINGUP = 'Стремеление к развитию'
export const PRODUCTORIENTATION = 'Ориентация на продукт'
export const PROACTION = 'Про-активность'
export const PEOPLEMANAGEMENT = 'Пипл-менеджмент'
